const lorem =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

export const portfolioData = {
  profile: {
    name: "DigiMarc",
    role: "3D Artist and Product Designer",
    summary:
      "Digital designer specialising in 3D modelling and UX, creating 3D assets, prototypes, iOS apps, and interface mockups for digital and physical products. Combines visual design with user-centred thinking to create engaging, functional experiences, with interests in product design, interactive media, and emerging technologies.",
  },
  resumeFile: "Marco Sihombing CV, 2026.pdf.pdf",
  contact: {
    heading: "Let's Connect!",
    lead: "Reach me on my socials!",
    links: [
      {
        label: "Instagram",
        url: "https://www.instagram.com/digitalmarc_/?hl=en",
        handle: "@digitalmarc_",
        icon: "assets/icons/instaicon.png",
      },
      {
        label: "LinkedIn",
        url: "https://www.linkedin.com/in/marco-sihombing-8b12a4289",
        handle: "marco-sihombing-8b12a4289",
        icon: "assets/icons/linkedin-logo.png",
      },
      {
        label: "Google Drive",
        url: "https://drive.google.com/drive/folders/1-SY9PJKRtUcRG209PiY5O-jtWgyNlu-b?usp=sharing",
        handle: "Portfolio Drive",
        icon: "assets/icons/googledrive.png",
      },
      {
        label: "Email",
        url: "mailto:marco.reinhard2@gmail.com",
        handle: "marco.reinhard2@gmail.com",
        icon: "assets/icons/outlook.png",
      },
    ],
  },
  categories: [
    {
      id: "models",
      title: "3D Models",
      description: "Characters, Mascots, and Objects created for various projects.",
      projects: [
        {
          slug: "dewata-masks-assets",
          title: "Dewata Masks Assets",
          type: "image",
          folder: "3D MODELS/BARONG PASAR DEWATA",
          cover: "BARONG SS FROM PASAR DEWATA.png",
          assets: [
            { folder: "3D MODELS/BARONG PASAR DEWATA", file: "BARONG SS FROM PASAR DEWATA.png" },
            { folder: "3D MODELS/BARONG PASAR DEWATA", file: "baronganimationtrial0054.png" },
            { folder: "3D MODELS/BARONG PASAR DEWATA", file: "BarongColorTest.png" },
            { folder: "3D MODELS/RANGDA PASAR DEWATA", file: "RANGDA SS FROM PASARDEWATA.png" },
            { folder: "3D MODELS/RANGDA PASAR DEWATA", file: "Rangdaanimations0064.png" },
            { folder: "3D MODELS/RANGDA PASAR DEWATA", file: "Rangdaanimations0746.png" },
          ],
          description: lorem,
        },
        {
          slug: "bmo",
          title: "BMO",
          type: "image",
          folder: "3D MODELS/BMO MODEL",
          cover: "BMO2.png",
          gallery: ["BMO3.png"],
          description: lorem,
        },
        {
          slug: "caishen-cny-mascot",
          title: "Caishen CNY Mascot",
          type: "image",
          folder: "3D MODELS/CAISHEN MASCOT CNY",
          cover: "CAISHED MASCOT RENDERS/CAISHENKASIANGPAODEPAN.png",
          gallery: [
            "CAISHED MASCOT RENDERS/CAISHENKASIANGPAOSAMPING.png",
            "CAISHED MASCOT RENDERS/CaishenLEMPARBG2.png",
            "CAISHED MASCOT RENDERS/CaishenSAMPINGATASpng.png",
            "CAISHEN MASCOT USED/CaishenBillboard1.jpeg",
            "CAISHEN MASCOT USED/CaishenDeskDisplay.jpeg",
            "CAISHEN MASCOT USED/CaishenElavatorwrappedbetter.jpeg",
            "CAISHEN MASCOT USED/CaishenLobbyPoster.jpeg",
            "CAISHEN MASCOT USED/CaisshenBilboard2.jpeg",
          ],
          description: lorem,
        },
        {
          slug: "chinese-wood-snake-cny",
          title: "Wooden Snake CNY Mascot",
          type: "image",
          folder: "3D MODELS/CHINESE WOOD SNAKE MASCOT CNY",
          cover: "WOODSNAKE2.png",
          gallery: [
           
            "WOODSNAKE2.png",
            "WOODSNAKEFORMALL.png",
            "WOODSNAKE UNFINISHED.png",
            "WOODSNAKEFORMALL2.png",
            "WoodsnakeMascotIG.jpeg",
          ],
          description: lorem,
        },
        {
          slug: "corgy-cupid-valentines",
          title: "Corgy Cupid Valentine's Mascot",
          type: "image",
          folder: "3D MODELS/CORGY CUPID VALENTINE'S",
          cover: "FINALS.jpg",
          gallery: ["Gizmocupid2.png", "Gizmocupid3.png"],
          description: lorem,
        },
        {
          slug: "memories-digital-environment",
          title: "MEMORIES Digital Environment",
          type: "image",
          folder: "3D MODELS/MEMORIES Digital Environment",
          cover: "3D WORLD 1.png",
          gallery: [
            "3D WORLD 10.png",
            "3D WORLD 11.png",
            "3D WORLD 12.png",
            "3D WORLD 13.png",
            "3D WORLD 2.png",
            "3D WORLD 3.png",
            "3D WORLD 4.png",
            "3D WORLD 5.png",
            "3D WORLD 6.png",
            "3D WORLD 7.png",
            "3D WORLD 8.png",
            "3D WORLD 9.png",
          ],
          description: lorem,
        },
        {
          slug: "ramadhan-assets-pack",
          title: "Ramadhan Assets Pack, Pillar",
          type: "image",
          folder: "3D MODELS/RAMADHAN ASSETS PACK, PILLAR",
          cover: "RAMADHANPILLAR3.png",
          gallery: ["RAMADHANPILLAR3.png", "RAMADHANPILLER1.png"],
          description: lorem,
        },
        {
          slug: "tf2-dispenser-bmo",
          title: "TF2 Dispenser with BMO",
          type: "image",
          folder: "3D MODELS/TF2 DISPENSER WITH BMO",
          cover: "DispenserandBMO.png",
          gallery: ["DispenserandBMO2.png", "DispenserandBMO3.png"],
          description: lorem,
        },
        {
          slug: "sinatra-snowglobe",
          title: "More Projects Coming Soon!",
          type: "image",
          folder: "3D MODELS/Projects Coming Soon",
          cover: null,
          gallery: [],
          mediaPending: true,
          description: lorem,
        },
      ],
    },
    {
      id: "moving",
      title: "Moving Arts",
      description: "Films, Animations, and Moving Artworks",
      projects: [
        {
          slug: "morph-film",
          title: "MORPH film",
          type: "youtube",
          youtubeUrl: "https://www.youtube.com/watch?v=OiueORk0xVU",
          folder: "MOVING ARTS/MORPH FILM",
          cover: "ScreeniefromMorph.png",
          gallery: [],
          description: lorem,
        },
        {
          slug: "pasar-dewata-film",
          title: "PASAR DEWATA film",
          type: "youtube",
          youtubeUrl: "https://www.youtube.com/watch?v=i6RhDN2EUJA",
          folder: "MOVING ARTS/PASAR DEWATA FILM",
          cover: "Pasar Dewata Screenshots from the film/0533.png",
          gallery: [
            "Pasar Dewata Screenshots from the film/0082.png",
            "Pasar Dewata Screenshots from the film/0122.png",
            "Pasar Dewata Screenshots from the film/0136.png",
            "Pasar Dewata Screenshots from the film/0151.png",
            "Pasar Dewata Screenshots from the film/0201.png",
            "Pasar Dewata Screenshots from the film/0230.png",
            "Pasar Dewata Screenshots from the film/0247.png",
            "Pasar Dewata Screenshots from the film/0303.png",
            "Pasar Dewata Screenshots from the film/0533.png",
          ],
          description: lorem,
        },
      ],
    },
    {
      id: "mockups",
      title: "Product Physical Mockups",
      description: "Signage Designs, Product Mockups, and Prototypes",
      projects: [
        {
          slug: "uwalk-signage-goofyv",
          title: "UWALK Signage Designs Goofyv",
          type: "image",
          folder: "PRODUCT PHYSICAL MOCKUPS/UWALK SIGNAGE DESIGNS GOOFY",
          cover: "SIGNAGEGOOFY 2 P1.png",
          gallery: [
            "SIGNAGEGOOFY 2 P2.png",
            "SIGNAGEGOOFY 3 P1.png",
            "SIGNAGEGOOFY 3 P3.png",
            "SIGNAGEGOOFY1.png",
            "SIGNAGEGOOFY3 P2.png",
            "SIGNAGEGOOFY4P1.png",
            "SIGNAGEGOOFY4P2.png",
            "SIGNAGEGOOFY4P3.png",
          ],
          description: lorem,
        },
        {
          slug: "uwalk-signage-modernv",
          title: "UWALK Signage Designs Modernv",
          type: "image",
          folder: "PRODUCT PHYSICAL MOCKUPS/UWALK SIGNAGE DESIGNS MODERN",
          cover: "SIGNAGEDESIGNMODERNALL.png",
          gallery: [
            "SIGNAGEDESIGNMODERN1P2.png",
            "SIGNAGEDESIGNMODERN2P1.png",
            "SIGNAGEDESIGNMODERN2P2.png",
            "SIGNAGEDESIGNMODERN3P1.png",
            "SIGNAGEDESIGNMODERN3P2.png",
            "SIGNAGEDESIGNMODERN4P1.png",
            "SIGNAGEDESIGNMODERN4P2.png",
            "SIGNAGEDESIGNMODERN5P1.png",
            "SIGNAGEDESIGNMODERN5P2.png",
            "SIGNAGEDESIGNMODERNALL.png",
          ],
          description: lorem,
        },
      ],
    },
  ],
};
